-- Automatisch erzeugt von scripts/gen-events-seed.ts — nicht von Hand bearbeiten.
-- Übernimmt die 43 kuratierten Events aus lib/events.ts in die Tabelle.
-- Idempotent: erneutes Ausführen aktualisiert bestehende Zeilen anhand des slug.

insert into events
  (slug, date, sport, promotion, title, main, fighter_a, fighter_b, venue, broadcaster, note, undercard)
values
  ('oktagon-93', '2026-09-12', 'MMA', 'OKTAGON', 'OKTAGON 93: Roušal vs. Mågård', 'Roušal vs. Mågård', 'Roušal', 'Mågård', 'Winning Group Arena, Brno', 'DAZN', 'Featherweight main event between Czech home favorite Radek Roušal (on a four-fight finishing streak) and former two-time OKTAGON champion Jonas "Shark" Mågård. The original Brito vs. Gogoladze title fight was pulled from this card after Brito vacated the belt and signed with the UFC.', array['Kalašnik vs. Rayomba', 'Kinehan vs. Cook', 'Bruknar vs. Haywood']),
  ('phoenix-fc5', '2026-09-19', 'MMA', 'Phoenix Fighting Championship', 'PFC 5', 'Rundsporthalle Baunatal card', null, null, 'Rundsporthalle, Baunatal', '-', 'MMA & K1, an explosive fight night.', '{}'),
  ('oktagon-94', '2026-09-26', 'MMA', 'OKTAGON', 'OKTAGON 94: The Biggest Comeback Ever', 'Frankfurt stadium card', null, null, 'Deutsche Bank Park, Frankfurt', 'DAZN / RTL+', 'In 2024, OKTAGON broke the MMA world attendance record here with 60,000 fans. Comeback show in the same stadium.', '{}'),
  ('steko-1', '2026-10-03', 'Boxing', 'STEKO''S Fight Night', 'World title fights, Munich', 'O. Plasene, C. Netza and others', null, null, 'Munich', '-', 'Multiple world title fights on one card.', '{}'),
  ('oktagon-95', '2026-10-17', 'MMA', 'OKTAGON', 'OKTAGON 95', 'Kincl vs. Humburger', 'Kincl', 'Humburger', 'KV Arena, Karlovy Vary', 'DAZN', 'Former champion Kincl against Humburger, a fight Humburger requested himself.', '{}'),
  ('rtl-freetv', '2026-10-18', 'MMA', 'OKTAGON', 'OKTAGON — Free-TV Premiere', 'Germany''s MMA elite in Cologne', null, null, 'Cologne', 'RTL (Free-TV)', 'MMA''s first-ever German free-TV broadcast — a statement for the sport''s future here.', '{}'),
  ('korn-hass', '2026-10-03', 'Muay Thai', 'K.O.RNHASS Fight Night', 'K.O.RNHASS Fight Night', 'K1 / MMA / Boxing / Muay Thai', null, null, 'Festival tent, Irschenberg', '-', 'Pro and amateur bouts, national and world title fights across multiple styles.', '{}'),
  ('sauerland-mf', '2026-11-07', 'Boxing', 'MF Sports (Sauerland)', 'MF Sports — Germany comeback', 'Card TBA', null, null, 'TBA, Germany', 'TBA', 'The Sauerland brothers are independent again and plan to promote in Germany again in 2026.', '{}'),
  ('glory-109', '2026-09-05', 'Kickboxing', 'GLORY', 'GLORY 109', 'Rotterdam fight card', null, null, 'RTM Stage, Rotterdam', '-', 'The world''s leading kickboxing promotion returns to its Rotterdam home venue.', '{}'),
  ('judo-grand-slam-hungary', '2026-09-11', 'Judo', 'IJF Judo Grand Slam', 'Judo Grand Slam Hungary', 'Elite -60kg to +100kg finals', null, null, 'Budapest, Hungary', 'IJF TV', 'One of the IJF''s premier annual Grand Slam stops, drawing Olympic medalists across all weight classes.', '{}'),
  ('adcc-2026', '2026-09-12', 'Jiu-Jitsu', 'ADCC', 'ADCC World Championship 2026', 'No-gi grappling''s biggest stage', null, null, 'Krakow, Poland', 'FloGrappling', 'Held every two years; the top submission grapplers across weight classes plus the openweight superfight.', '{}'),
  ('karate1-salzburg', '2026-10-02', 'Karate', 'WKF Karate 1', 'Karate 1 Series A Salzburg', 'Kumite & kata across all weight classes', null, null, 'Salzburg, Austria', '-', 'Part of the WKF''s global qualification series toward the 2026 Karate World Cup.', '{}'),
  ('uww-worlds-2026', '2026-10-24', 'Wrestling', 'UWW', 'World Wrestling Championships 2026', 'Freestyle, Greco-Roman & women''s wrestling', null, null, 'Astana, Kazakhstan', '-', 'Relocated from Bahrain; wrestling''s most important non-Olympic championship, running through Nov 1.', '{}'),
  ('wt-grand-prix-final', '2026-11-28', 'Taekwondo', 'World Taekwondo', 'World Taekwondo Grand Prix Final', 'Season finale — top 8 ranked fighters per division', null, null, 'Incheon, South Korea', '-', 'Exact date still TBA at time of writing (World Taekwondo lists Nov/Dec) — check worldtaekwondo.org closer to the date.', '{}'),
  ('ufc-331', '2026-09-19', 'MMA', 'UFC', 'UFC 331', 'Van vs. Pantoja 2', 'Van', 'Pantoja', 'Crypto.com Arena, Los Angeles', 'ESPN+/PPV', 'Flyweight title rematch between champion Joshua Van and former champion Alexandre Pantoja.', '{}'),
  ('ufc-332', '2026-10-03', 'MMA', 'UFC', 'UFC 332', 'Figueiredo vs. Talbott, plus a Shevchenko title defense', null, null, 'Delta Center, Salt Lake City', 'ESPN+/PPV', 'Two-time women''s flyweight champion Valentina Shevchenko defends against Natália Silva in the co-main.', array['Shevchenko vs. Silva']),
  ('ufc-333', '2026-10-24', 'MMA', 'UFC', 'UFC 333', 'Volkanovski vs. Evloev', 'Volkanovski', 'Evloev', 'Etihad Arena, Abu Dhabi', 'ESPN+/PPV', 'Featherweight title fight; Yan vs. Dvalishvili bantamweight trilogy co-headlines.', array['Yan vs. Dvalishvili']),
  ('ufc-334', '2026-11-14', 'MMA', 'UFC', 'UFC 334', 'Main event TBD', null, null, 'Madison Square Garden, New York City', 'ESPN+/PPV', 'UFC''s first Madison Square Garden card since UFC 322 in Nov 2025.', '{}'),
  ('oktagon-96', '2026-10-31', 'MMA', 'OKTAGON', 'OKTAGON 96', 'Gogoladze vs. Klinkhammer', 'Gogoladze', 'Klinkhammer', 'SAP Garden, Munich', 'DAZN / RTL+', 'Vacant welterweight title fight after Kaik Brito left the promotion.', '{}'),
  ('oktagon-97', '2026-11-07', 'MMA', 'OKTAGON', 'OKTAGON 97', 'Severino vs. Holzer', 'Severino', 'Holzer', 'ZAG Arena, Hannover', 'DAZN / RTL+', 'Bantamweight champion Severino defends against German challenger Max Holzer.', '{}'),
  ('dubois-wardley-2', '2026-10-17', 'Boxing', 'Queensberry Promotions', 'Dubois vs. Wardley II', 'Dubois vs. Wardley', 'Dubois', 'Wardley', 'The O2 Arena, London', '-', 'Rematch of a 2026 Fight of the Year contender.', '{}'),
  ('canelo-mbilli', '2026-10-31', 'Boxing', 'Riyadh Season', 'Canelo vs. Mbilli', 'Canelo vs. Mbilli', 'Canelo', 'Mbilli', 'Riyadh, Saudi Arabia', '-', 'Canelo challenges for Mbilli''s WBC super middleweight title, his first fight since losing to Crawford.', '{}'),
  ('glory-110', '2026-10-17', 'Kickboxing', 'GLORY', 'GLORY 110', 'Trindade vs. Demirkapu', 'Trindade', 'Demirkapu', 'Lotto Arena, Antwerp', '-', 'Vacant GLORY featherweight world title fight.', '{}'),
  ('glory-rivals-6', '2026-11-28', 'Kickboxing', 'GLORY', 'GLORY Rivals 6', 'Up-and-coming prospects card', null, null, 'Maaspoort, Den Bosch', '-', 'GLORY partners with Dutch regional promotion Ringfight Promotions to showcase rising talent.', '{}'),
  ('one-fight-night-48', '2026-10-03', 'MMA', 'ONE Championship', 'ONE Fight Night 48', 'Erdogan vs. Elliott', 'Erdogan', 'Elliott', 'Lumpinee Stadium, Bangkok', 'Prime Video', 'Shamil Erdogan (13-0) meets Paul Elliott with vacant ONE heavyweight MMA title implications on the line.', '{}'),
  ('one-samurai-4', '2026-10-17', 'Kickboxing', 'ONE Championship', 'ONE SAMURAI 4', 'Haggerty vs. Akimoto', 'Haggerty', 'Akimoto', 'Ariake Arena, Tokyo', '-', 'Jonathan Haggerty defends the ONE bantamweight kickboxing title against Hiroki Akimoto; Superlek vs. Jonathan Di Bella also headlines.', '{}'),
  ('oktagon-98', '2026-11-21', 'MMA', 'OKTAGON', 'OKTAGON 98', 'Card TBA', null, null, 'WERK ARENA, Třinec', 'DAZN', 'Main event not yet announced.', '{}'),
  ('one-samurai-5', '2026-11-18', 'Kickboxing', 'ONE Championship', 'ONE SAMURAI 5', 'Card TBA', null, null, 'EBARA WAVE Arena Ota, Tokyo', '-', 'Main event not yet announced.', '{}'),
  ('judo-grand-slam-tokyo', '2026-12-05', 'Judo', 'IJF Judo Grand Slam', 'Judo Grand Slam Tokyo', 'Elite finals across all weight classes', null, null, 'Tokyo, Japan', '-', 'The final Grand Slam of the 2026 IJF World Judo Tour season, held in judo''s Japanese heartland — a key world-ranking event.', '{}'),
  ('oktagon-99', '2026-12-05', 'MMA', 'OKTAGON', 'OKTAGON 99', 'Card TBA', null, null, 'Westfalenhalle, Dortmund', 'DAZN / RTL+', 'Main event not yet announced.', '{}'),
  ('one-fight-night-49', '2026-12-12', 'MMA', 'ONE Championship', 'ONE Fight Night 49', 'Card TBA', null, null, 'Lumpinee Stadium, Bangkok', '-', 'Main event not yet announced.', '{}'),
  ('ufc-335', '2026-12-12', 'MMA', 'UFC', 'UFC 335', 'Main event TBD', null, null, 'T-Mobile Arena, Las Vegas', 'ESPN+/PPV', 'Closes out the UFC''s 2026 numbered-event slate; no UFC events beyond this date are confirmed yet.', '{}'),
  ('glory-collision-10', '2026-12-12', 'Kickboxing', 'GLORY', 'GLORY Collision 10', 'Kromah vs. Plazibat', 'Kromah', 'Plazibat', 'GelreDome, Arnhem', '-', 'Heavyweight title fight; also features a Trindade vs. Demirkapu rematch of their GLORY 110 featherweight title bout.', array['Trindade vs. Demirkapu (rematch)']),
  ('oktagon-100', '2026-12-29', 'MMA', 'OKTAGON', 'OKTAGON 100', 'Card TBA', null, null, 'O2 Arena, Prague', 'DAZN', 'Milestone 100th numbered OKTAGON event, marketed as "100 tournaments, 10 years."', '{}'),
  ('k1-world-max-70kg-final', '2026-12-29', 'Kickboxing', 'K-1', 'K-1 World MAX 2026 — 70kg World Championship Final', '70kg tournament final', null, null, 'Yokohama Buntai, Yokohama', '-', 'Final of K-1''s flagship 70kg tournament, a separate promotion from GLORY giving kickboxing extra depth on the calendar.', '{}'),
  ('oktagon-stuttgart', '2027-01-16', 'MMA', 'OKTAGON', 'OKTAGON — Stuttgart', 'Card TBA', null, null, 'Hanns-Martin-Schleyer-Halle, Stuttgart', 'DAZN / RTL+', 'Main event and official numbering not yet announced.', '{}'),
  ('wkf-karate1-tbilisi', '2027-01-08', 'Karate', 'WKF Karate 1', 'Karate 1 Series A Tbilisi', 'Kumite & kata across all weight classes', null, null, 'Tbilisi, Georgia', '-', 'Part of the WKF''s global qualification series toward the 2027 season.', '{}'),
  ('ibjjf-euros-2027', '2027-01-13', 'Jiu-Jitsu', 'IBJJF', 'European IBJJF Jiu-Jitsu Championship 2027', 'Gi & no-gi divisions, all belt levels', null, null, 'Lisbon, Portugal', '-', 'The largest annual gi/no-gi European IBJJF title event, drawing thousands of competitors across all belt levels.', '{}'),
  ('wkf-karate1-istanbul', '2027-01-29', 'Karate', 'WKF Karate 1', 'Karate 1 Premier League Istanbul', 'Kumite & kata across all weight classes', null, null, 'Istanbul, Turkey', '-', 'A top-tier Premier League leg feeding Olympic-cycle world rankings.', '{}'),
  ('uww-zagreb-open-2027', '2027-02-04', 'Wrestling', 'UWW', 'UWW Ranking Series — Zagreb Open 2027', 'Freestyle, Greco-Roman & women''s wrestling', null, null, 'Zagreb, Croatia', '-', 'Traditionally the season-opening leg of United World Wrestling''s Ranking Series, drawing top senior wrestlers across all styles.', '{}'),
  ('wkf-karate1-rome', '2027-03-11', 'Karate', 'WKF Karate 1', 'Karate 1 Premier League Rome', 'Kumite & kata across all weight classes', null, null, 'Rome, Italy', '-', 'A top-tier Premier League leg feeding Olympic-cycle world rankings.', '{}'),
  ('wt-grand-prix-paris-2027', '2027-08-29', 'Taekwondo', 'World Taekwondo', 'World Taekwondo Grand Prix II — Paris', 'Finals across all Olympic weight divisions', null, null, 'Paris, France', '-', 'Second leg of the 2027 Grand Prix series, running August 26-29, 2027; date shown is the finals day.', '{}'),
  ('wt-grand-prix-final-2027', '2027-12-05', 'Taekwondo', 'World Taekwondo', 'World Taekwondo Grand Prix Final', 'Season finale — top ranked fighters per division', null, null, 'Tai''an, China', '-', 'Caps the 2027 Grand Prix series, running December 3-5, 2027; date shown is the finals day.', '{}')
on conflict (slug) do update set
  date        = excluded.date,
  sport       = excluded.sport,
  promotion   = excluded.promotion,
  title       = excluded.title,
  main        = excluded.main,
  fighter_a   = excluded.fighter_a,
  fighter_b   = excluded.fighter_b,
  venue       = excluded.venue,
  broadcaster = excluded.broadcaster,
  note        = excluded.note,
  undercard   = excluded.undercard,
  updated_at  = now();
